### ISSUE TITLE
Перестал парсить

### ISSUE THREAD

**Issue by develflowing** [netunormalnihnikov/Scrapy_sber#2]
Доброго дня.

На прошлой неделе все прекрасно работало, сегодня походу что то СМ поправили на своей стороне, в логах появилось такое сообщение: GOOD proxy became DEAD
Прокси видимо подключается, но после повторной попытки скачивания, получает отлуп от СМ.
Не сталкивались?

Спасибо.

**Comment by netunormalnihnikov** [comment]
Исправлена ошибка загрузки изображений. Возможно проблема была связана с этим. Проверьте.

**Comment by netunormalnihnikov** [comment]
> Доброго дня.
> 
> На прошлой неделе все прекрасно работало, сегодня походу что то СМ поправили на своей стороне, в логах появилось такое сообщение: GOOD proxy became DEAD Прокси видимо подключается, но после повторной попытки скачивания, получает отлуп от СМ. Не сталкивались?
> 
> Спасибо.

Исправлена ошибка загрузки изображений. Проверьте, скорее всего Ваша ошибка также устранена.
Если ошибка остается, то попробуйте клонировать в отдельный проект и заново установить зависимости.
Сообщите результат.

**Comment by develflowing** [comment]
Доброго.
Загрузка изображений отключена. Поправил код в остальных функциях, ошибка сохранилась. Стопорится тут:
`2022-08-12 11:17:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://sbermarket.ru/api/categories?store_id=2956> (referer: https://sbermarket.ru/magnit_express/)`

`2022-08-12 11:17:27 [scrapy.downloadermiddlewares.cookies] DEBUG: Sending cookies to: <GET https://sbermarket.ru/api/stores/2956/products?tid=snova-v-shkolu%2Fpismennie-chertezhnie-prinadlezhnosti%2Fkarandashi-grifeli&page=1&per_page=20&sort=popularity>
Cookie: external_analytics_anonymous_id=a3c0b657-9083-4de2-bebf-c3103037d4d9`

Список категорий получает, но в категории провалиться не может. Через Postman я так же не смог получить доступ к категориям, как будто сменилась выдача у СМ. По ссылкам отдает 404.

**Comment by develflowing** [comment]
Само заработало. Спасибо!

**Comment by develflowing** [comment]
Доброго дня!
Ошибка вернулась, предполагаю, что СМ встроили защиту, т.к. в браузере начало появляться сообщение о проверке браузера. Видимо что-то в cookies подкидывают, что scrapy переварить не может.

**Comment by netunormalnihnikov** [comment]
Занимаюсь поиском обхода.
